language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - gfortran
    - clang
    - libz-dev
    - libbz2-dev
    - libblas-dev
    - liblapack-dev
    - libarpack2-dev
    - libnetcdf-dev
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev

matrix:
  include:
    - { os: linux, env: PYVER=2 NOCONDA=""}
    - { os: linux, env: PYVER=3 NOCONDA=""}
    - { os: osx, env: PYVER=2 NOCONDA=""}
    - { os: osx, env: PYVER=3 NOCONDA=""}
    - { os: linux, env: PYVER=2 NOCONDA="--non-conda"}
    - { os: linux, env: PYVER=3 NOCONDA="--non-conda"}
    - { os: osx, env: PYVER=2 NOCONDA="--non-conda"}
    - { os: osx, env: PYVER=3 NOCONDA="--non-conda"}

sudo: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      brew tap homebrew/science;
      brew update;
      sudo bash scripts/install_gfortran.sh;
    fi
  - if [[ "$NOCONDA" = "--non-conda" ]]; then
      pip install numpy --user;
      pip install nglview --user;
      pip install ipython==5.3.0;
      pip install ipywidgets --user;
    fi

install:
    - bash install_ambertools.sh --prefix $HOME/ -v $PYVER $NOCONDA
    - source $HOME/amber17/amber.sh

script:
    - tleap -h
    - sqm -h
    # - sander -h # sander -h exit 1, ack
    - cpptraj -h
    - python -c "import parmed; print(parmed)"
    - python -c "import sander; print(sander)"
    - python -c "import pytraj; print(pytraj)"
    - source scripts/dummy.sh

after_success:
    - echo "hello there"
    
notifications:
  email: false
