language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - gfortran
    - clang
    - libz-dev
    - libbz2-dev
    - libblas-dev
    - liblapack-dev
    - libarpack2-dev
    - libnetcdf-dev
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev

matrix:
  include:
    - { os: linux }
    - { os: osx }

sudo: true

before_install:
  - source scripts/dummy.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew tap homebrew/science;
      brew update;
      sudo bash scripts/install_gfortran.sh;
    fi

install:
    - cp scripts/.amberrc $HOME/
    - source install_ambertools.sh --prefix $HOME/

script:
    - tleap -h
    - sqm -h
    # - sander -h # sander -h exit 1, ack
    - cpptraj -h
    - python -c "import parmed; print(parmed)"
    - python -c "import sander; print(sander)"
    - python -c "import pytraj; print(pytraj)"
    - python -c "import nglview; print(nglview)"   

after_success:
    - echo "hello there"

notifications:
  email: false
